export type WeeklyStatus = {
  readonly week: string;
  readonly status: OkrStatus;
  readonly note: string;
  readonly pathToGreen: string;
  readonly planDone: boolean;
  readonly updatedAt: string;
  readonly author: string;
};
export type OkrItem = {
  readonly id: string;
  readonly objective: string;
  readonly keyResults: string;
  readonly actualKeyResults: string;
  readonly projectIds: readonly string[];
  readonly startDate: string;
  readonly endDate: string;
  readonly weeklyStatuses: readonly WeeklyStatus[];
};

export const OKR_STATUSES = ["Pending", "Green", "Yellow", "Red"] as const;
export type OkrStatus = typeof OKR_STATUSES[number];
export const OKR_LIFECYCLES = ["Draft", "Active", "Closed", "Archived"] as const;
export type OkrLifecycle = typeof OKR_LIFECYCLES[number];
export type AuditEntry = {
  readonly id: string;
  readonly at: string;
  readonly author: string;
  readonly reason: string;
  readonly before: string;
  readonly after: string;
};
export type TaskLink = { readonly taskId: string; readonly title: string; readonly contribution: string };
export type CheckIn = {
  readonly id: string;
  readonly createdAt: string;
  readonly author: string;
  readonly measuredOn: string;
  readonly periodStart: string;
  readonly value: number | null;
  readonly status: OkrStatus;
  readonly note: string;
  readonly evidence: string;
  readonly blockers: string;
  readonly nextAction: string;
  readonly nextReview: string;
  readonly reflection: string;
  readonly planId: string;
  readonly definitionVersion: number;
  readonly unit: string;
  readonly measurementDefinition: string;
  readonly supersedes: string;
  readonly correctionReason: string;
};
export type RecoveryAction = {
  readonly id: string;
  readonly title: string;
  readonly effect: string;
  readonly ownerId: string;
  readonly dueDate: string;
  readonly status: "To do" | "In progress" | "Done";
};
export type RecoveryPlan = {
  readonly id: string;
  readonly problem: string;
  readonly cause: string;
  readonly support: string;
  readonly returnCriteria: string;
  readonly nextReview: string;
  readonly state: "Open" | "Closed";
  readonly verification: string;
  readonly actions: readonly RecoveryAction[];
  readonly taskLinks: readonly TaskLink[];
  readonly riskIds: readonly string[];
  readonly history: readonly AuditEntry[];
};
export type Retrospective = {
  readonly id: string;
  readonly at: string;
  readonly author: string;
  readonly result: "Met" | "Not met" | "Inconclusive";
  readonly evidence: string;
  readonly executionEffect: string;
  readonly lessons: string;
  readonly carryForward: string;
};
export type KeyResult = {
  readonly id: string;
  readonly title: string;
  readonly ownerId: string;
  readonly startDate: string;
  readonly endDate: string;
  readonly lifecycle: OkrLifecycle;
  readonly baseline: number;
  readonly baselineDate: string;
  readonly target: number;
  readonly unit: string;
  readonly direction: "Increase" | "Decrease";
  readonly successCriteria: string;
  readonly guardrails: string;
  readonly definition: string;
  readonly scope: string;
  readonly aggregation: string;
  readonly cadenceDays: number;
  readonly source: string;
  readonly referenceUrl: string;
  readonly definitionVersion: number;
  readonly checkIns: readonly CheckIn[];
  readonly taskLinks: readonly TaskLink[];
  readonly plans: readonly RecoveryPlan[];
  readonly retrospectives: readonly Retrospective[];
  readonly history: readonly AuditEntry[];
};
export type Objective = {
  readonly id: string;
  readonly title: string;
  readonly change: string;
  readonly why: string;
  readonly ownerId: string;
  readonly startDate: string;
  readonly endDate: string;
  readonly lifecycle: OkrLifecycle;
  readonly keyResults: readonly KeyResult[];
  readonly history: readonly AuditEntry[];
};
